apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels: 
    name: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 8040
    name: http
    protocol: TCP
  selector:
    name: auth-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auth-server
  template:
    metadata:
      labels: 
        name: auth-server
    spec:
      containers:
        - name: auth-server
          image: jiangpeipei/auth-server:1.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8040
