---
apiVersion: v1
kind: Service
metadata:
  name: google
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  asds
      prefix: /sf/
      service: shopfront:8010
spec:
  type: ClusterIP
  clusterIP: None
